mongoDB
J-Bannach/21ideas pull request #17
Opened 2021-06-17 12:45 UTC by J-Bannach

- Install mongoDB
- Connect to mongoDB
- Test write/read in mongoDB

2021-06-17 13:39 UTC, lmachens requested changes

2021-06-17 13:39 UTC, lmachens commented on samples.http
> +POST {{baseURL}}/api/credentials HTTP/1.1
`credentials`? Your project is about recipes.

2021-06-18 08:08 UTC, l-goede approved these changes
lgtm!:)

2021-06-18 08:12 UTC, daebert approved these changes
Lgtm!

2021-06-18 08:13 UTC, roabram approved these changes
lgtm 💯

2021-06-18 08:14 UTC, Niklas-Schaefers approved these changes
lgtm 🚀

2021-06-18 08:39 UTC, merged