✨ Add Home page
J-Bannach/21ideas pull request #33
Opened 2021-06-26 19:30 UTC by J-Bannach

Home page consists of:
- overview of days 
- meals per day
- select function for meals (functionality not yet implemented)

2021-06-26 19:37 UTC, MaxMuecket approved these changes
lgtm ✌️

I'm not sure, but maybe this is the reason why your App isn't deploying.

2021-06-26 19:37 UTC, MaxMuecket commented on src/app/components/DaysAndMeals/DaysAndMeals.stories.tsx
> +  component: 'DaysAndMeals',
```suggestion
  component: DaysAndMeals,
```

2021-06-26 19:37 UTC, MaxMuecket commented on src/app/components/SelectionBlock/SelectionBlock.stories.tsx
>    component: 'SelectionBlock',
```suggestion
  component: SelectionBlock,
```

2021-06-27 03:56 UTC, lmachens requested changes
gj
Changes are requested because of failing deployment.

2021-06-27 03:56 UTC, lmachens commented on src/app/components/SelectionBlock/SelectionBlock.tsx
> +      <br />
You use `br` to create a gap, but this is not how a `br` should be used for:

> Note: Do not use `<br>` to create margins between paragraphs; wrap them in `<p>` elements and use the CSS margin property to control their size.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

Alternatives:
1) Create blocks
```tsx
  <div>
    <MealSelection link="./search" />
    <MealSelection link="./search" />
    <MealSelection link="./search" />
  </div>
  <div>
    <MealSelection link="./search" />
    <MealSelection link="./search" />
    <MealSelection link="./search" />
  </div>
```
You can style the gap by setting `margin` on the new `div` elements or `row-gap` on the parent grid.

2) Use `:nth-child` CSS selector

```css
.selectionBlock:nth-child(3n) {
  margin-bottom: 1em;
}
```
See https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

2021-06-27 09:51 UTC, J-Bannach commented on src/app/components/DaysAndMeals/DaysAndMeals.stories.tsx
> +  component: 'DaysAndMeals',
Changed it, thanks.

2021-06-27 10:22 UTC, J-Bannach commented on src/app/components/SelectionBlock/SelectionBlock.tsx
> +      <br />
Thanks, I changed it now to div elements.

2021-06-27 10:23 UTC, merged